const WORLD_SEQUENCE = ['strings', 'brass', 'woodwinds', 'percussion', 'finale'];

const WORLD_DATA = {
  hub: {
    id: 'hub',
    type: 'hub',
    title: 'Grand Concert Hall',
    shortTitle: 'Hub',
    theme: 'The central overworld map where every reclaimed section returns to the stage.',
    section: 'Orchestra',
    environment: 'Concert Hall Hub',
    statusLabel: 'Starting Area',
    goal: 'Choose a door, enter a corrupted section world, and begin restoring the lost symphony.',
    missingTarget: 'The conductor score has been shattered across the section worlds.',
    battleStyle: 'No battle here. The hub is for navigation, story setup, and orchestra assembly.',
    unlocks: ['strings', 'brass', 'woodwinds', 'percussion'],
    reward: 'Once every section returns, the final concert route opens.',
    mechanics: ['World selection', 'Story recap', 'Recovered section roster', 'Finale gate'],
    npcIdeas: ['Stage manager', 'Archivist', 'Concertmaster ghost light'],
    itemIdeas: ['Broken score fragment', 'Season program', 'Stage pass']
  },
  strings: {
    id: 'strings',
    type: 'world',
    title: 'String Forest',
    shortTitle: 'Strings',
    theme: 'A dense forest of bow-lines and echoing harmonics where fast patterns tangle the path.',
    section: 'Strings',
    environment: 'Forest World',
    statusLabel: 'World One',
    goal: 'Find the missing string leader and recover the stolen melody shard.',
    missingTarget: 'A principal violinist hidden behind corrupted rhythm vines.',
    battleStyle: 'Fast, high-stamina combat rhythm challenge tied to bowing precision and repeated patterns.',
    unlocks: ['brass'],
    reward: 'Strings rejoin the orchestra and reopen the brass gate in the hub.',
    mechanics: ['Rapid rhythm inputs', 'Trail exploration', 'Melody shard recovery'],
    npcIdeas: ['Lost violinist', 'Forest luthier', 'Echo sprite'],
    itemIdeas: ['Bow of resonance', 'Rosin crystal', 'Melody shard']
  },
  brass: {
    id: 'brass',
    type: 'world',
    title: 'Brass Fortress',
    shortTitle: 'Brass',
    theme: 'A fortified citadel of fanfares, valves, and towering harmonic walls.',
    section: 'Brass',
    environment: 'Fortress World',
    statusLabel: 'World Two',
    goal: 'Reach the upper tower and reclaim the brass captain from the corrupted fanfare engine.',
    missingTarget: 'A horn or trumpet leader trapped in the resonance chamber.',
    battleStyle: 'Slow but powerful pitch-matching encounters with heavier impact windows.',
    unlocks: ['woodwinds'],
    reward: 'Brass returns with the fortress key that opens the woodwind route.',
    mechanics: ['Pitch locks', 'Fortress switches', 'Power timing windows'],
    npcIdeas: ['Trumpet herald', 'Horn sentinel', 'Valve smith'],
    itemIdeas: ['Fanfare crest', 'Valve key', 'Golden mute']
  },
  woodwinds: {
    id: 'woodwinds',
    type: 'world',
    title: 'Woodwind Wilds',
    shortTitle: 'Woodwinds',
    theme: 'A shifting grove of reeds, breath currents, and winding melodic trails.',
    section: 'Woodwinds',
    environment: 'Grove World',
    statusLabel: 'World Three',
    goal: 'Follow the breath-paths to gather the scattered players before the harmony dissolves.',
    missingTarget: 'A captured soloist hidden among looping phrase winds.',
    battleStyle: 'Pattern recognition and phrase-matching with lighter, more fluid timing.',
    unlocks: ['percussion'],
    reward: 'Woodwinds restore the color voices of the orchestra and reveal the percussion pass.',
    mechanics: ['Phrase puzzles', 'Air-current navigation', 'Section-call rescue'],
    npcIdeas: ['Oboe guide', 'Clarinet twins', 'Bassoon mapkeeper'],
    itemIdeas: ['Reed bundle', 'Phrase compass', 'Harmony leaf']
  },
  percussion: {
    id: 'percussion',
    type: 'world',
    title: 'Percussion Peaks',
    shortTitle: 'Percussion',
    theme: 'A mountainous rhythm realm powered by pulse engines, drums, and impact bridges.',
    section: 'Percussion',
    environment: 'Mountain World',
    statusLabel: 'World Four',
    goal: 'Climb the pulse towers and retune the beat cores before the whole symphony collapses.',
    missingTarget: 'A timpani master locked in the summit metronome.',
    battleStyle: 'Pure rhythm combat with layered patterns and escalating tempo pressure.',
    unlocks: ['finale'],
    reward: 'Percussion restores the orchestra heartbeat and unlocks the final concert.',
    mechanics: ['Beat lanes', 'Tempo climbs', 'Summit pulse cores'],
    npcIdeas: ['Timpani keeper', 'Snare runner', 'Bell ringer'],
    itemIdeas: ['Pulse crystal', 'Mallet sigil', 'Tempo core']
  },
  finale: {
    id: 'finale',
    type: 'finale',
    title: 'Final Concert',
    shortTitle: 'Finale',
    theme: 'The restored orchestra returns to the main stage for a culminating PSO performance unlock.',
    section: 'Full Orchestra',
    environment: 'Concert Finale',
    statusLabel: 'Final Reward',
    goal: 'Assemble every reclaimed section, complete the finale setup, and unlock a real PSO recording.',
    missingTarget: 'No section is missing once the symphony is fully restored.',
    battleStyle: 'Uses recovered sections instead of a normal battle. Can later integrate Orchestra Builder or a final conducting sequence.',
    unlocks: [],
    reward: 'A real Poway Symphony Orchestra recording and full orchestra celebration scene.',
    mechanics: ['Recovered roster check', 'Finale setup', 'Recording unlock'],
    npcIdeas: ['Conductor', 'Full section leaders', 'Audience usher'],
    itemIdeas: ['Complete score', 'Concert baton', 'Performance seal']
  }
};

export { WORLD_DATA, WORLD_SEQUENCE };